from typing import Protocol

from smtr.memory.schemas import ExecutionEvidence, MemoryRoutingCard, ProcedurePayload
from smtr.memory.snapshot import MemoryStoreSnapshot


class SharedMemoryRepository(Protocol):
    def create_memory(self, payload: ProcedurePayload, card: MemoryRoutingCard) -> None: ...

    def get_routing_cards(self) -> list[MemoryRoutingCard]: ...

    def get_routing_card(self, memory_id: str) -> MemoryRoutingCard: ...

    def get_payload(self, memory_id: str, version: int | None = None) -> ProcedurePayload: ...

    def get_selected_payloads(self, memory_ids: list[str]) -> list[ProcedurePayload]: ...

    def record_execution_evidence(self, evidence: ExecutionEvidence) -> None: ...

    def current_revision(self) -> int: ...

    def create_read_snapshot(self) -> MemoryStoreSnapshot: ...
