"""Shared Memory Pool M^t for RIMA (Phase 5).

Paper definition::

    M^t = union_{tau < t} union_i m_i^tau

``M^t`` contains ONLY memories generated by strictly earlier tasks. The
strong invariant::

    memory.origin_task_position < current_task_position

is enforced at admission of candidates into any retrieval at task ``t``.
``M^t`` is distinct from per-receiver knowledge states ``K_r^t`` (Phase 6).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

__all__ = [
    "SharedMemory",
    "SharedMemoryPool",
    "TemporalLeakageError",
]


class TemporalLeakageError(RuntimeError):
    """Raised when a memory from task >= t enters the candidate set at t."""


@dataclass(frozen=True)
class SharedMemory:
    """One entry of the shared memory pool.

    Attributes:
        memory_id: unique identifier.
        source_agent_id: agent that produced the memory.
        origin_task_id: task where the experience was extracted.
        origin_task_position: ordinal position of the origin task
            (strict monotonic timeline; the temporal-leakage guard key).
        routing_card: critic-visible routing card (payload NOT included).
        procedure_payload: execution-visible procedure content
            (sanitized; never visible to the critic).
        scenario: MultiAgentBench domain of origin.
        created_at: UTC creation timestamp.
    """

    memory_id: str
    source_agent_id: str
    origin_task_id: str
    origin_task_position: int
    routing_card: dict[str, Any] = field(default_factory=dict)
    procedure_payload: str = ""
    scenario: str = ""
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


def _relevance_score(memory: SharedMemory, task: dict[str, Any]) -> float:
    """Deterministic lexical relevance between routing card and task text.

    Deliberately simple and dependency-free; retrieval here is the shared
    candidate-generation step, and downstream ranking is the critic's job.
    """
    task_tokens = set(str(task.get("text", "") or task.get("description", "")).lower().split())
    task_tokens |= {str(t).lower() for t in task.get("tags", []) or []}
    card_tokens = {str(t).lower() for t in memory.routing_card.get("task_tags", []) or []}
    goal_tokens = set(str(memory.routing_card.get("goal_summary", "")).lower().split())
    union = card_tokens | goal_tokens
    if not union or not task_tokens:
        return 0.0
    return len(task_tokens & union) / len(union)


class SharedMemoryPool:
    """The shared pool M^t (all agents' historical memories).

    Invariants:

    * ``memories_before(task_position)`` returns only memories with
      ``origin_task_position < task_position``;
    * ``retrieve`` operates on ``memories_before`` of the CURRENT task,
      so current-task-generated memories can never be retrieved for the
      current task (Phase 8).
    """

    def __init__(self) -> None:
        self._memories: dict[str, SharedMemory] = {}
        self._order: list[str] = []

    def add(self, memory: SharedMemory) -> None:
        if memory.memory_id in self._memories:
            raise ValueError(f"Duplicate memory_id: {memory.memory_id!r}")
        self._memories[memory.memory_id] = memory
        self._order.append(memory.memory_id)

    def add_many(self, memories: list[SharedMemory]) -> None:
        for m in memories:
            self.add(m)

    def __len__(self) -> int:
        return len(self._memories)

    def __contains__(self, memory_id: str) -> bool:
        return memory_id in self._memories

    def get(self, memory_id: str) -> SharedMemory:
        return self._memories[memory_id]

    def memories_before(self, task_position: int) -> list[SharedMemory]:
        """All memories originating from tasks strictly before ``task_position``."""
        return [
            self._memories[mid]
            for mid in self._order
            if self._memories[mid].origin_task_position < task_position
        ]

    def retrieve(
        self,
        task: dict[str, Any],
        receiver: str,
        top_k: int,
        *,
        current_task_position: int,
    ) -> list[SharedMemory]:
        """Receiver-conditioned candidate retrieval C_r^t.

        Only historical memories (origin_task_position < current_task_position)
        are eligible. Self-transfer pairs (source == receiver) may appear in
        C_r^t but MUST be excluded at the admission stage with status
        ``SELF_TRANSFER_EXCLUDED`` and counted (Phase 12).
        """
        eligible = self.memories_before(current_task_position)
        scored = sorted(
            eligible,
            key=lambda m: (-_relevance_score(m, task), m.memory_id),
        )
        return scored[: max(0, top_k)]
